### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by 2A5F** [volight/darl#12]
- 2.x
  - [ ] 支持纯 cli 使用
- 3.0
  - [ ] 使用 ink 重写 
  - [ ] 支持分离进程输出
  - [ ] 支持记录进程输出到文件
  - [ ] 改进 .js 控制方式从配置式到调用式
  - [ ] 直接运行 node_module 内安装的 bin 包而无需使用 npm script
